# Generated by Django 4.2.7 on 2025-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudyRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="自习室名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("capacity", models.PositiveIntegerField(verbose_name="容量")),
                ("location", models.CharField(max_length=200, verbose_name="位置")),
                ("equipment", models.TextField(blank=True, verbose_name="设备")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="room_images/",
                        verbose_name="图片",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "自习室",
                "verbose_name_plural": "自习室",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="时间段名称")),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "时间段",
                "verbose_name_plural": "时间段",
                "ordering": ["start_time"],
            },
        ),
    ]
