# Generated by Django 4.2.7 on 2025-05-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("all", "所有测试"),
                            ("unit", "单元测试"),
                            ("integration", "集成测试"),
                            ("performance", "性能测试"),
                            ("models", "模型测试"),
                            ("views", "视图测试"),
                            ("api", "API测试"),
                            ("coverage", "覆盖率测试"),
                            ("lint", "代码检查"),
                            ("security", "安全检查"),
                            ("full", "完整测试"),
                        ],
                        max_length=20,
                        verbose_name="测试类型",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度")),
                (
                    "result_data",
                    models.TextField(blank=True, null=True, verbose_name="结果数据"),
                ),
                ("success_rate", models.FloatField(default=0.0, verbose_name="成功率")),
            ],
            options={
                "verbose_name": "测试运行",
                "verbose_name_plural": "测试运行",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=255, verbose_name="测试名称")),
                ("status", models.CharField(max_length=20, verbose_name="状态")),
                ("duration", models.FloatField(default=0.0, verbose_name="耗时(秒)")),
                ("output", models.TextField(blank=True, null=True, verbose_name="输出")),
                ("error", models.TextField(blank=True, null=True, verbose_name="错误")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "test_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="test_dashboard.testrun",
                        verbose_name="测试运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试结果",
                "verbose_name_plural": "测试结果",
                "ordering": ["created_at"],
            },
        ),
    ]
